### ISSUE TITLE
not showing loot

### ISSUE THREAD

**Issue by MityTin** [Mojito-Fivem/mojito_qb-zombies#1]
I installed qb zombie on qb core server but error showing loot map e

**Comment by GreenBeardJames** [comment]
same 
script:core script error: invalid lua type: no value
script:core> SetDrawOrigin (SetDrawOrigin.lua:17)
script:core>ref (@qb-core/client/functions.lua:34)
script:core> fn @qb-xombies/client/main.lua:336)

**Comment by Mojito-Fivem** [comment]
If you fix it then pull request the repo, I'm not going to fix this script because I don't care.
