### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by colormeblind23** [Mojito-Fivem/mojito_qb-zombies#2]
![image](https://user-images.githubusercontent.com/15605562/124463604-1f340080-dd61-11eb-8e24-0f200b8aa4cf.png)
Looting comes back with this error when standing near a dead zombie
![image](https://user-images.githubusercontent.com/15605562/124463668-383cb180-dd61-11eb-9736-f910a69e54cf.png)
This second error appears upon spawning into the game

**Comment by Mojito-Fivem** [comment]
I refer to #1 if you can fix it do a PR, otherwise I don't care.

**Comment by colormeblind23** [comment]
I made the issue to see if you could help but if you don't care then its whatever xD
